name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version used to tag the images'
        required: true
        default: 'latest'
      arch:
        description: 'The architecture the image should be build for'
        required: true
        default: 'arm64'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
          VERSION=${{ github.event.inputs.version }}
          ARCH=${{ github.event.inputs.arch }}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=arch::${ARCH}
      - name: Docker Build (build)
        run: |
          docker build -t ghcr.io/holzeis/speedtest:${{ steps.prepare.outputs.version }} --build-arg ARCH=${{ steps.prepare.outputs.arch }} .
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Docker Build (push)
        run: |
          docker push ghcr.io/holzeis/speedtest:${{ steps.prepare.outputs.version }}
      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
